/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RemindersIndexRouteImport } from './routes/reminders/index'
import { Route as InviteGroupsIndexRouteImport } from './routes/invite-groups/index'
import { Route as FamiliesIndexRouteImport } from './routes/families/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as RemindersNewRouteImport } from './routes/reminders/new'
import { Route as InviteGroupsNewRouteImport } from './routes/invite-groups/new'
import { Route as InviteGroupsIdRouteImport } from './routes/invite-groups/$id'
import { Route as FamiliesNewRouteImport } from './routes/families/new'
import { Route as FamiliesIdRouteImport } from './routes/families/$id'
import { Route as EventsNewRouteImport } from './routes/events/new'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as DemoDbChatApiRouteImport } from './routes/demo/db-chat-api'
import { Route as DemoDbChatRouteImport } from './routes/demo/db-chat'
import { Route as ContactsNewRouteImport } from './routes/contacts/new'
import { Route as ContactsIdRouteImport } from './routes/contacts/$id'
import { Route as EventsUpcomingIndexRouteImport } from './routes/events/upcoming/index'
import { Route as EventsTemplatesIndexRouteImport } from './routes/events/templates/index'
import { Route as FamiliesIdEditRouteImport } from './routes/families/$id/edit'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ContactsIdEditRouteImport } from './routes/contacts/$id/edit'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersIndexRoute = RemindersIndexRouteImport.update({
  id: '/reminders/',
  path: '/reminders/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteGroupsIndexRoute = InviteGroupsIndexRouteImport.update({
  id: '/invite-groups/',
  path: '/invite-groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesIndexRoute = FamiliesIndexRouteImport.update({
  id: '/families/',
  path: '/families/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersNewRoute = RemindersNewRouteImport.update({
  id: '/reminders/new',
  path: '/reminders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteGroupsNewRoute = InviteGroupsNewRouteImport.update({
  id: '/invite-groups/new',
  path: '/invite-groups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteGroupsIdRoute = InviteGroupsIdRouteImport.update({
  id: '/invite-groups/$id',
  path: '/invite-groups/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesNewRoute = FamiliesNewRouteImport.update({
  id: '/families/new',
  path: '/families/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesIdRoute = FamiliesIdRouteImport.update({
  id: '/families/$id',
  path: '/families/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatApiRoute = DemoDbChatApiRouteImport.update({
  id: '/demo/db-chat-api',
  path: '/demo/db-chat-api',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDbChatRoute = DemoDbChatRouteImport.update({
  id: '/demo/db-chat',
  path: '/demo/db-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsNewRoute = ContactsNewRouteImport.update({
  id: '/contacts/new',
  path: '/contacts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIdRoute = ContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsUpcomingIndexRoute = EventsUpcomingIndexRouteImport.update({
  id: '/events/upcoming/',
  path: '/events/upcoming/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsTemplatesIndexRoute = EventsTemplatesIndexRouteImport.update({
  id: '/events/templates/',
  path: '/events/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesIdEditRoute = FamiliesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => FamiliesIdRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIdEditRoute = ContactsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ContactsIdRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/contacts/$id': typeof ContactsIdRouteWithChildren
  '/contacts/new': typeof ContactsNewRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/events/new': typeof EventsNewRoute
  '/families/$id': typeof FamiliesIdRouteWithChildren
  '/families/new': typeof FamiliesNewRoute
  '/invite-groups/$id': typeof InviteGroupsIdRoute
  '/invite-groups/new': typeof InviteGroupsNewRoute
  '/reminders/new': typeof RemindersNewRoute
  '/calendar/': typeof CalendarIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/families/': typeof FamiliesIndexRoute
  '/invite-groups/': typeof InviteGroupsIndexRoute
  '/reminders/': typeof RemindersIndexRoute
  '/contacts/$id/edit': typeof ContactsIdEditRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/families/$id/edit': typeof FamiliesIdEditRoute
  '/events/templates/': typeof EventsTemplatesIndexRoute
  '/events/upcoming/': typeof EventsUpcomingIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/contacts/$id': typeof ContactsIdRouteWithChildren
  '/contacts/new': typeof ContactsNewRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/events/new': typeof EventsNewRoute
  '/families/$id': typeof FamiliesIdRouteWithChildren
  '/families/new': typeof FamiliesNewRoute
  '/invite-groups/$id': typeof InviteGroupsIdRoute
  '/invite-groups/new': typeof InviteGroupsNewRoute
  '/reminders/new': typeof RemindersNewRoute
  '/calendar': typeof CalendarIndexRoute
  '/contacts': typeof ContactsIndexRoute
  '/events': typeof EventsIndexRoute
  '/families': typeof FamiliesIndexRoute
  '/invite-groups': typeof InviteGroupsIndexRoute
  '/reminders': typeof RemindersIndexRoute
  '/contacts/$id/edit': typeof ContactsIdEditRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/families/$id/edit': typeof FamiliesIdEditRoute
  '/events/templates': typeof EventsTemplatesIndexRoute
  '/events/upcoming': typeof EventsUpcomingIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/contacts/$id': typeof ContactsIdRouteWithChildren
  '/contacts/new': typeof ContactsNewRoute
  '/demo/db-chat': typeof DemoDbChatRoute
  '/demo/db-chat-api': typeof DemoDbChatApiRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/events/new': typeof EventsNewRoute
  '/families/$id': typeof FamiliesIdRouteWithChildren
  '/families/new': typeof FamiliesNewRoute
  '/invite-groups/$id': typeof InviteGroupsIdRoute
  '/invite-groups/new': typeof InviteGroupsNewRoute
  '/reminders/new': typeof RemindersNewRoute
  '/calendar/': typeof CalendarIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/families/': typeof FamiliesIndexRoute
  '/invite-groups/': typeof InviteGroupsIndexRoute
  '/reminders/': typeof RemindersIndexRoute
  '/contacts/$id/edit': typeof ContactsIdEditRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/families/$id/edit': typeof FamiliesIdEditRoute
  '/events/templates/': typeof EventsTemplatesIndexRoute
  '/events/upcoming/': typeof EventsUpcomingIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/contacts/$id'
    | '/contacts/new'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/prisma'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/events/new'
    | '/families/$id'
    | '/families/new'
    | '/invite-groups/$id'
    | '/invite-groups/new'
    | '/reminders/new'
    | '/calendar/'
    | '/contacts/'
    | '/events/'
    | '/families/'
    | '/invite-groups/'
    | '/reminders/'
    | '/contacts/$id/edit'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/families/$id/edit'
    | '/events/templates/'
    | '/events/upcoming/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/contacts/$id'
    | '/contacts/new'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/prisma'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/events/new'
    | '/families/$id'
    | '/families/new'
    | '/invite-groups/$id'
    | '/invite-groups/new'
    | '/reminders/new'
    | '/calendar'
    | '/contacts'
    | '/events'
    | '/families'
    | '/invite-groups'
    | '/reminders'
    | '/contacts/$id/edit'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/families/$id/edit'
    | '/events/templates'
    | '/events/upcoming'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/contacts/$id'
    | '/contacts/new'
    | '/demo/db-chat'
    | '/demo/db-chat-api'
    | '/demo/prisma'
    | '/demo/store'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/events/new'
    | '/families/$id'
    | '/families/new'
    | '/invite-groups/$id'
    | '/invite-groups/new'
    | '/reminders/new'
    | '/calendar/'
    | '/contacts/'
    | '/events/'
    | '/families/'
    | '/invite-groups/'
    | '/reminders/'
    | '/contacts/$id/edit'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/families/$id/edit'
    | '/events/templates/'
    | '/events/upcoming/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ContactsIdRoute: typeof ContactsIdRouteWithChildren
  ContactsNewRoute: typeof ContactsNewRoute
  DemoDbChatRoute: typeof DemoDbChatRoute
  DemoDbChatApiRoute: typeof DemoDbChatApiRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  EventsNewRoute: typeof EventsNewRoute
  FamiliesIdRoute: typeof FamiliesIdRouteWithChildren
  FamiliesNewRoute: typeof FamiliesNewRoute
  InviteGroupsIdRoute: typeof InviteGroupsIdRoute
  InviteGroupsNewRoute: typeof InviteGroupsNewRoute
  RemindersNewRoute: typeof RemindersNewRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  FamiliesIndexRoute: typeof FamiliesIndexRoute
  InviteGroupsIndexRoute: typeof InviteGroupsIndexRoute
  RemindersIndexRoute: typeof RemindersIndexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  EventsTemplatesIndexRoute: typeof EventsTemplatesIndexRoute
  EventsUpcomingIndexRoute: typeof EventsUpcomingIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/': {
      id: '/reminders/'
      path: '/reminders'
      fullPath: '/reminders/'
      preLoaderRoute: typeof RemindersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite-groups/': {
      id: '/invite-groups/'
      path: '/invite-groups'
      fullPath: '/invite-groups/'
      preLoaderRoute: typeof InviteGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/': {
      id: '/families/'
      path: '/families'
      fullPath: '/families/'
      preLoaderRoute: typeof FamiliesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/new': {
      id: '/reminders/new'
      path: '/reminders/new'
      fullPath: '/reminders/new'
      preLoaderRoute: typeof RemindersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite-groups/new': {
      id: '/invite-groups/new'
      path: '/invite-groups/new'
      fullPath: '/invite-groups/new'
      preLoaderRoute: typeof InviteGroupsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite-groups/$id': {
      id: '/invite-groups/$id'
      path: '/invite-groups/$id'
      fullPath: '/invite-groups/$id'
      preLoaderRoute: typeof InviteGroupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/new': {
      id: '/families/new'
      path: '/families/new'
      fullPath: '/families/new'
      preLoaderRoute: typeof FamiliesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/$id': {
      id: '/families/$id'
      path: '/families/$id'
      fullPath: '/families/$id'
      preLoaderRoute: typeof FamiliesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat-api': {
      id: '/demo/db-chat-api'
      path: '/demo/db-chat-api'
      fullPath: '/demo/db-chat-api'
      preLoaderRoute: typeof DemoDbChatApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/db-chat': {
      id: '/demo/db-chat'
      path: '/demo/db-chat'
      fullPath: '/demo/db-chat'
      preLoaderRoute: typeof DemoDbChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/new': {
      id: '/contacts/new'
      path: '/contacts/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof ContactsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$id': {
      id: '/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof ContactsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/upcoming/': {
      id: '/events/upcoming/'
      path: '/events/upcoming'
      fullPath: '/events/upcoming/'
      preLoaderRoute: typeof EventsUpcomingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/templates/': {
      id: '/events/templates/'
      path: '/events/templates'
      fullPath: '/events/templates/'
      preLoaderRoute: typeof EventsTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/$id/edit': {
      id: '/families/$id/edit'
      path: '/edit'
      fullPath: '/families/$id/edit'
      preLoaderRoute: typeof FamiliesIdEditRouteImport
      parentRoute: typeof FamiliesIdRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$id/edit': {
      id: '/contacts/$id/edit'
      path: '/edit'
      fullPath: '/contacts/$id/edit'
      preLoaderRoute: typeof ContactsIdEditRouteImport
      parentRoute: typeof ContactsIdRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ContactsIdRouteChildren {
  ContactsIdEditRoute: typeof ContactsIdEditRoute
}

const ContactsIdRouteChildren: ContactsIdRouteChildren = {
  ContactsIdEditRoute: ContactsIdEditRoute,
}

const ContactsIdRouteWithChildren = ContactsIdRoute._addFileChildren(
  ContactsIdRouteChildren,
)

interface FamiliesIdRouteChildren {
  FamiliesIdEditRoute: typeof FamiliesIdEditRoute
}

const FamiliesIdRouteChildren: FamiliesIdRouteChildren = {
  FamiliesIdEditRoute: FamiliesIdEditRoute,
}

const FamiliesIdRouteWithChildren = FamiliesIdRoute._addFileChildren(
  FamiliesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ContactsIdRoute: ContactsIdRouteWithChildren,
  ContactsNewRoute: ContactsNewRoute,
  DemoDbChatRoute: DemoDbChatRoute,
  DemoDbChatApiRoute: DemoDbChatApiRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  EventsNewRoute: EventsNewRoute,
  FamiliesIdRoute: FamiliesIdRouteWithChildren,
  FamiliesNewRoute: FamiliesNewRoute,
  InviteGroupsIdRoute: InviteGroupsIdRoute,
  InviteGroupsNewRoute: InviteGroupsNewRoute,
  RemindersNewRoute: RemindersNewRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  FamiliesIndexRoute: FamiliesIndexRoute,
  InviteGroupsIndexRoute: InviteGroupsIndexRoute,
  RemindersIndexRoute: RemindersIndexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  EventsTemplatesIndexRoute: EventsTemplatesIndexRoute,
  EventsUpcomingIndexRoute: EventsUpcomingIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
